services:
  pgsql:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ludwig
      POSTGRES_PASSWORD: some-random-password-8891
      POSTGRES_DB: harbingerdb
    ports:
      - "${DB_PGSQL_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - harbingernet

  mariadb:
    image: mariadb:12.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: some-random-password-6671
      MYSQL_DATABASE: harbingerdb
      MYSQL_USER: wolfgang
      MYSQL_PASSWORD: some-random-password-0019
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - harbingernet

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: some-random-password-7811
      MYSQL_DATABASE: harbingerdb
      MYSQL_USER: vivaldi
      MYSQL_PASSWORD: some-random-password-6711
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - harbingernet

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - "8080:8080"
      networks:
        - harbingernet

volumes:
  pgdata:
  mariadbdata:
  mysqldata:

networks:
  harbingernet:
    driver: bridge
