services:
  pgsql:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_PGSQL_USERNAME}
      POSTGRES_PASSWORD: ${DB_PGSQL_PASSWORD}
      POSTGRES_DB: ${DB_PGSQL_DATABASE}
    ports:
      - "${DB_PGSQL_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - harbingernet

  mariadb:
    image: mariadb:12.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MARIA_PASSWORD}
      MYSQL_DATABASE: ${DB_MARIA_DATABASE}
      MYSQL_USER: ${DB_MARIA_USERNAME}
      MYSQL_PASSWORD: ${DB_MARIA_PASSWORD}
    ports:
      - "${DB_MARIA_PORT:-3306}:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - harbingernet

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
      MYSQL_USER: ${DB_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    ports:
      - "${DB_MYSQL_PORT:-3306}:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - harbingernet

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - harbingernet

volumes:
  pgdata:
  mariadbdata:
  mysqldata:

networks:
  harbingernet:
    driver: bridge
